### ISSUE TITLE
What would be the attributes of base?

### ISSUE THREAD

**Issue by gyanaggarwal** [jdkr/HaskellArchitectureProposal#1]
What would be the attributes of base?

Functions in base must not be safe at all cost.

I believe it should read as follow

Functions in base must be safe at all cost.

**Comment by jdkr** [comment]
No, I wrote it correctly. There are currently already a lot of unsafe functions in base. There are ongoing discussions to remove these parts, at least some. I am opposite to this view, as this will break a lot of codebases. 
Furthermore, in my opinion there should also be parts in base that are at a lower level in order to be able to write high-performance libraries. This implies some unsafety. But these unsafe functions should not be in the prelude. Currently people often take the lower level functions from the GHC module in base. But that's wrong. GHC is not Haskell, it's just a Haskell compiler.

The safeness can be implemented up to any desired degree in the core libraries. As I tried to explain, the set of core libraries should not be fixed, but there could be introduced some sort of trust level for a core library.
